/common/home/hz624/anaconda3/envs/AIOS/lib/python3.11/site-packages/transformers/utils/hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
Attack started at: 2024-07-28 23:31
Namespace(llm_name='ollama/llama3.1:8b', max_gpu_memory=None, eval_device=None, max_new_tokens=512, scheduler_log_mode='console', agent_log_mode='console', llm_kernel_log_mode='console', use_backend=None, workflow_mode='manual', attacker_tools_path='data/07282305.jsonl', tasks_path='data/agent_task_test.jsonl', tools_info_path='data/all_normal_tools.jsonl', observation_prompt_injection=False, plan_attack=False, action_attack=False, direct_prompt_injection=True, attack_type='naive', cot_backdoor=False)
[ðŸ¤–ollama/llama3.1:8b] AIOS LLM successfully loaded.

Total number of attacks: 0
Number of successful attacks: 0
Number of workflow generation failures: 0
Number of tool calling success: 0
Traceback (most recent call last):
  File "/common/users/hz624/AgentAttackBench/main_attacker.py", line 175, in <module>
    main()
  File "/common/users/hz624/AgentAttackBench/main_attacker.py", line 163, in main
    print(f"Attack success rate: {attack_succ/len(agent_tasks)}")
                                  ~~~~~~~~~~~^~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
Exception ignored in: <module 'threading' from '/common/home/hz624/anaconda3/envs/AIOS/lib/python3.11/threading.py'>
Traceback (most recent call last):
  File "/common/home/hz624/anaconda3/envs/AIOS/lib/python3.11/threading.py", line 1590, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
/common/home/hz624/anaconda3/envs/AIOS/lib/python3.11/site-packages/transformers/utils/hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
Attack started at: 2024-07-29 22:08
Namespace(llm_name='ollama/llama3.1:8b', max_gpu_memory=None, eval_device=None, max_new_tokens=512, scheduler_log_mode='console', agent_log_mode='console', llm_kernel_log_mode='console', use_backend=None, workflow_mode='manual', attacker_tools_path='data/attack_tools_test.jsonl', tasks_path='data/agent_task_test.jsonl', tools_info_path='data/all_normal_tools.jsonl', observation_prompt_injection=False, plan_attack=False, action_attack=False, direct_prompt_injection=True, attack_type='naive', cot_backdoor=False)
[ðŸ¤–ollama/llama3.1:8b] AIOS LLM successfully loaded.

Traceback (most recent call last):
  File "/common/users/hz624/AgentAttackBench/main_attacker.py", line 177, in <module>
    main()
  File "/common/users/hz624/AgentAttackBench/main_attacker.py", line 105, in main
    attacker_tools_all = pd.read_json(args.attacker_tools_path, lines=True)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/common/home/hz624/anaconda3/envs/AIOS/lib/python3.11/site-packages/pandas/io/json/_json.py", line 815, in read_json
    return json_reader.read()
           ^^^^^^^^^^^^^^^^^^
  File "/common/home/hz624/anaconda3/envs/AIOS/lib/python3.11/site-packages/pandas/io/json/_json.py", line 1023, in read
    obj = self._get_object_parser(self._combine_lines(data_lines))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/common/home/hz624/anaconda3/envs/AIOS/lib/python3.11/site-packages/pandas/io/json/_json.py", line 1051, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/common/home/hz624/anaconda3/envs/AIOS/lib/python3.11/site-packages/pandas/io/json/_json.py", line 1187, in parse
    self._parse()
  File "/common/home/hz624/anaconda3/envs/AIOS/lib/python3.11/site-packages/pandas/io/json/_json.py", line 1403, in _parse
    ujson_loads(json, precise_float=self.precise_float), dtype=None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Expected object or value
Exception ignored in: <module 'threading' from '/common/home/hz624/anaconda3/envs/AIOS/lib/python3.11/threading.py'>
Traceback (most recent call last):
  File "/common/home/hz624/anaconda3/envs/AIOS/lib/python3.11/threading.py", line 1590, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
