/common/home/hz624/anaconda3/envs/AIOS/lib/python3.11/site-packages/transformers/utils/hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
Attack started at: 2024-07-20 11:02
Namespace(llm_name='gpt-4o-mini', max_gpu_memory=None, eval_device=None, max_new_tokens=256, scheduler_log_mode='console', agent_log_mode='console', llm_kernel_log_mode='console', use_backend=None, workflow_mode='automatic', attacker_tools_path='data/test.jsonl', tasks_path='data/agent_tasks/example/academic_agent_task.txt', agent_path='example/academic_agent_attack', observation_prompt_injection=True, plan_attack=False, action_attack=False, direct_prompt_injection=False, attack_type=None)
Traceback (most recent call last):
  File "/common/users/hz624/AgentAttackBench/main_attacker.py", line 147, in <module>
    main()
  File "/common/users/hz624/AgentAttackBench/main_attacker.py", line 74, in main
    llm = llms.LLMKernel(
          ^^^^^^^^^^^^^^^
  File "/common/users/hz624/AgentAttackBench/aios/llm_core/llms.py", line 24, in __init__
    self.model = MODEL_REGISTRY[llm_name](
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/common/users/hz624/AgentAttackBench/aios/llm_core/llm_classes/gpt_llm.py", line 18, in __init__
    super().__init__(llm_name,
  File "/common/users/hz624/AgentAttackBench/aios/llm_core/llm_classes/base_llm.py", line 29, in __init__
    self.context_manager = SimpleContextManager()
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/common/users/hz624/AgentAttackBench/aios/context/simple_context.py", line 14, in __init__
    BaseContextManager.__init__(self)
  File "/common/users/hz624/AgentAttackBench/aios/context/base.py", line 10, in __init__
    os.makedirs(self.context_dir)
  File "<frozen os>", line 225, in makedirs
FileExistsError: [Errno 17] File exists: '/common/users/hz624/AgentAttackBench/aios/context/context_restoration'
